name: spoonacular_api
description: A new Flutter package.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http:
  json_annotation:


dev_dependencies:
  test:
  build_runner:
  json_serializable:
  mockito:
