name: recipe_repository
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  spoonacular_api:
    path: ../spoonacular_api
  equatable:

dev_dependencies:
  pedantic: ^1.9.0
